### ISSUE TITLE
Place for discussions

### ISSUE THREAD

**Issue by lextiz** [mrkent/open-government#1]
Hello @mrkent, very nice article. The idea of open-sourced government is very actual today, but for some reason not very popular. This topic is huge and at least consists from some sub-topics: collective decision making (like https://www.loomio.org), project tracking (like JIRA), government services (https://en.wikipedia.org/wiki/E-government) , also context-aware system that integrates three previous topics would be essential. Each of these topics is a serious project on its own, so I think some platform discussions would be needed (loomio?), or do you think Github issues and wiki is good enough?
Regarding concurrent governments: how would they share resources if their "members" are located in the same territory?

**Comment by mrkent** [comment]
@lextiz Sorry for late reply. 

> Each of these topics is a serious project on its own, so I think some platform discussions would be needed (loomio?), or do you think Github issues and wiki is good enough?

I don't know much about loomio, but my concept of an open source government is very abstract. Each "government" is more or less a dictatorship, controlled by the maintainers of the repository. Changes can be made through pull requests, but it's up to the maintainers whether to include them. If the population wants the new change, and maintainers refuse to include, they can simply subscribe to the fork. Now the person maintaining the new fork is the dictator. A core belief in my theory is based on [Voice vs Exit](https://www.youtube.com/watch?v=cOubCHLXT6A). The ease of exit gives power to voice. 

> Regarding concurrent governments: how would they share resources if their "members" are located in the same territory?

I don't claim I know how to manage such a government, merely that with this scheme, those that know can compete to create the best governments. 

How did you find this BTW?

**Comment by lextiz** [comment]
I have found this repo while searching github for something like "opensource government" striving to find opensource projects that develop system for society self ruling and collaborative decisions making to contribute to. I did not get from the beginning that the purpose of this repo is to focus on the theory.

**Comment by mrkent** [comment]
@lextiz Thanks. Happy to hear your thoughts/feedback on the topic.
